- build.gradle
- src/main/java/com/sw/cmc/adapter/in/TempControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/persistence/TempRepository.java
- src/main/java/com/sw/cmc/application/port/in/TempUseCase.java
- src/main/java/com/sw/cmc/application/service/TempService.java
- src/main/java/com/sw/cmc/common/advice/TempAdvice.java
- src/main/java/com/sw/cmc/common/config/TempConfig.java
- src/main/java/com/sw/cmc/common/util/TempUtil.java
- src/main/java/com/sw/cmc/domain/TempDomain.java
- src/main/resources/openapi_cmc/cmc.yaml
- src/main/resources/openapi_cmc/dto/CmcDTO.yaml
- src/main/resources/openapi_cmc/entity/CmcEntity.yaml
> ➕: 프로젝트 초기 설정

- .gitignore
- build.gradle
- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/java/com/sw/cmc/common/config/XssFilterConfig.java
- src/main/java/com/sw/cmc/common/filter/XssFilter.java
- src/main/resources/application.properties
- src/main/resources/application.yaml
> ✨: DB 연결 설정

- .gitignore
- build.gradle
- src/main/java/com/sw/cmc/adapter/in/TempControllerImpl.java
- src/main/resources/application.yaml
swagger-ui.html 정상 노출 확인
Resolves: #6
>  ✨: swagger, springdoc 설정

- src/main/java/com/sw/cmc/CmcApplication.java
> ✨ just test

- src/main/java/com/sw/cmc/adapter/in/user/LoginControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/persistence/user/LoginRepository.java
- src/main/java/com/sw/cmc/application/port/in/user/LoginUseCase.java
- src/main/java/com/sw/cmc/application/service/user/LoginService.java
- src/main/java/com/sw/cmc/common/config/JwtProperties.java
- src/main/java/com/sw/cmc/common/jwt/JwtTokenProvider.java
- src/main/java/com/sw/cmc/common/jwt/JwtTokenType.java
- src/main/java/com/sw/cmc/common/util/LoginUtil.java
- src/main/java/com/sw/cmc/domain/user/TempLogin.java
- src/main/java/com/sw/cmc/domain/user/Token.java
- src/main/resources/application.yaml
- src/main/resources/openapi_cmc/dto/LoginDTO.yaml
- src/main/resources/openapi_cmc/entity/UserEntity.yaml
> ✨ 임시로그인 와꾸잡기

- build.gradle
- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/domain/user/Join.java
- src/main/java/com/sw/cmc/domain/user/TempLogin.java
- src/main/resources/openapi_cmc/entity/UserEntity.yaml
> ✏️ Dtm -> At 변경

- src/main/resources/application.yaml
- src/main/resources/schema.sql
ddl-auto: none
schema.spl 파일 생성
Related to: #9
>  ✨: jpa 설정

- src/main/resources/schema.sql
> 🔨: updated_at 미동작으로 인해 data type 변경

- src/main/resources/schema.sql
> 🔨: db table 명 snake case로 변경

- build.gradle
- src/main/java/com/sw/cmc/adapter/in/user/JoinControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/persistence/user/JoinRepository.java
- src/main/java/com/sw/cmc/application/port/in/user/JoinUseCase.java
- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/domain/user/Join.java
- src/main/java/com/sw/cmc/domain/user/TempLogin.java
- src/main/resources/openapi_cmc/dto/user/JoinDTO.yaml
- src/main/resources/openapi_cmc/entity/UserEntity.yaml
- src/main/resources/openapi_cmc/user.yaml
> ✅ 임시로그인 로직

- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/common/jwt/JwtTokenProvider.java
- src/main/java/com/sw/cmc/common/util/LoginUtil.java
- src/main/java/com/sw/cmc/domain/user/Join.java
> ⚡️ static으로

- src/main/resources/schema.sql
> ✨: db cascade delete 옵션 추가

- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/domain/user/Join.java
- src/main/resources/openapi_cmc/entity/UserEntity.yaml
> ⚡️ 타임스탬프 업데이트

- build.gradle
- src/main/java/com/sw/cmc/adapter/in/comment/CommentControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/comment/persistence/CommentRepository.java
- src/main/java/com/sw/cmc/application/port/in/comment/CommentUseCase.java
- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/domain/comment/CommentDomain.java
- src/main/resources/openapi_cmc/comment.yaml
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
- src/main/resources/openapi_cmc/entity/CommentEntity.yaml
> ✨: 댓글 생성 api 작업

- src/main/java/com/sw/cmc/adapter/in/comment/CommentControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/comment/CommentUseCase.java
- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/domain/comment/CommentDomain.java
- src/main/resources/openapi_cmc/comment.yaml
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ✨ :  댓글 삭제 api 개발

- src/main/java/com/sw/cmc/adapter/in/comment/CommentControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/comment/CommentUseCase.java
- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/resources/openapi_cmc/comment.yaml
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ✨: 댓글 단건 조회

- src/main/java/com/sw/cmc/adapter/in/comment/web/CommentControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/like/web/LikeControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/notice/web/NoticeControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/user/web/JoinControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/user/web/LoginControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/view/web/ViewControllerImpl.java
> 🚚: adapter.in.web 폴더 생성 및 컨트롤러 파일 이동

- build.gradle
- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/java/com/sw/cmc/adapter/in/smtp/event/SmtpEventListener.java
- src/main/java/com/sw/cmc/application/port/in/smtp/SmtpUseCase.java
- src/main/java/com/sw/cmc/application/service/notice/NoticeService.java
- src/main/java/com/sw/cmc/application/service/smtp/SmtpService.java
- src/main/java/com/sw/cmc/domain/smtp/SendEmailDomain.java
- src/main/java/com/sw/cmc/event/notice/SendNotiEmailEvent.java
- src/main/resources/application.yaml
> ✨: SMTP 서비스 작업

- build.gradle
- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveChatControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveChatRepository.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepository.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveChatUseCase.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveCodingUseCase.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveChatService.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/common/config/CorsConfig.java
- src/main/java/com/sw/cmc/common/config/WebSocketConfig.java
- src/main/java/com/sw/cmc/domain/lcd/LiveChatDomain.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingDomain.java
- src/main/java/com/sw/cmc/domain/lcd/webSocketMessage.java
- src/main/resources/openapi_cmc/dto/lcd/LiveChatDTO.yaml
- src/main/resources/openapi_cmc/dto/lcd/LiveCodingDTO.yaml
- src/main/resources/openapi_cmc/entity/LiveChatEntity.yaml
- src/main/resources/openapi_cmc/entity/LiveCodingEntity.yaml
- src/main/resources/openapi_cmc/livecode.yaml
- src/main/resources/static/chat.js
- src/main/resources/static/index.html
> ✨: 실시간 공유 페이지 작업

- src/main/java/com/sw/cmc/adapter/in/user/web/JoinControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/user/web/LoginControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/user/JoinUseCase.java
- src/main/java/com/sw/cmc/application/port/in/user/LoginUseCase.java
- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/application/service/user/LoginService.java
- src/main/java/com/sw/cmc/domain/user/JoinDomain.java
- src/main/java/com/sw/cmc/domain/user/TempLoginDomain.java
- src/main/resources/openapi_cmc/dto/user/JoinDTO.yaml
- src/main/resources/openapi_cmc/dto/user/TempLoginDTO.yaml
- src/main/resources/openapi_cmc/user.yaml
> ⏪️ dto명 변경

- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveChatControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveChatRepository.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepository.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveChatUseCase.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveCodingUseCase.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveChatService.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/common/config/CorsConfig.java
- src/main/java/com/sw/cmc/common/config/WebSocketConfig.java
- src/main/java/com/sw/cmc/domain/lcd/LiveChatDomain.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingDomain.java
- src/main/java/com/sw/cmc/domain/lcd/webSocketMessage.java
1. javac description 작성
2. 컨트롤러 @PostMapping 제거 
3. repsitory 수정 (domain -> entity)
5. usecase javadoc 작성
6. EnableJpaAuditing 제거 (@PrePersist 사용)
Related to: #37
> ♻️: 라이브코딩 리팩토링

- src/main/java/com/sw/cmc/adapter/in/comment/web/CommentControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/comment/persistence/CommentRepository.java
- src/main/java/com/sw/cmc/application/port/in/comment/CommentUseCase.java
- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/domain/comment/CommentDomain.java
- src/main/java/com/sw/cmc/domain/comment/CommentListDomain.java
- src/main/resources/openapi_cmc/comment.yaml
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
- src/main/resources/openapi_cmc/entity/CommentEntity.yaml
> ✨: target_id별 댓글 다건 조회 구현

- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/entity/Comment.java
> 🔨: entity 변경으로 인한 코드 수정

- build.gradle
- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/java/com/sw/cmc/application/service/ai/AIService.java
- src/main/java/com/sw/cmc/common/config/GptConfig.java
- src/main/resources/application.yaml
> ✨ : open ai 연결 설정 및 가이드 코드

- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/application/service/like/LikeService.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/application/service/user/JoinService.java
- src/main/java/com/sw/cmc/application/service/user/LoginService.java
- src/main/java/com/sw/cmc/application/service/view/ViewService.java
- src/main/java/com/sw/cmc/common/advice/CmcControllerAdvice.java
- src/main/java/com/sw/cmc/domain/user/UserDomain.java
> ♻️ : CmcException 사용 방법 변경

- build.gradle
- src/main/java/com/sw/cmc/common/config/P6SpyConfig.java
- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
> ⚡️: P6Spy 쿼리 로깅

- src/main/resources/openapi_cmc/livecode.yaml
> ✅ livecode.yaml 코드 수정

- src/main/java/com/sw/cmc/adapter/in/review/ReviewControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/review/ReviewUseCase.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
- src/main/resources/openapi_cmc/review.yaml
> ✨리뷰 등록 API 개발중 | 리뷰 생성 테스트까지 완료

- src/main/java/com/sw/cmc/adapter/in/redis/RedisControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/redis/RedisUseCase.java
- src/main/java/com/sw/cmc/application/service/redis/RedisService.java
- src/main/java/com/sw/cmc/domain/redis/RedisHashDomain.java
- src/main/resources/openapi_cmc/dto/redis/RedisDTO.yaml
- src/main/resources/openapi_cmc/redis.yaml
레디스 hash crud api 개발 (라이브코딩에서 해쉬로 사용) #42
> ✨: redis Hash CRUD API 개발  #42

- src/main/java/com/sw/cmc/adapter/in/redis/RedisControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/redis/RedisUseCase.java
- src/main/java/com/sw/cmc/application/service/redis/RedisService.java
- src/main/resources/openapi_cmc/redis.yaml
- /getAllRedis, /deleteHash 삭제
- 조회 api 수정 
- 해시 키 조회 api 수정 
#41
> ♻️: 레디스 api 리팩토링 

- src/main/java/com/sw/cmc/adapter/in/comment/web/CommentControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/review/ReviewControllerImpl.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/java/com/sw/cmc/entity/Review.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> ✨리뷰 생성 API 개발 | 2차 수정 (컬럼 추가 버전까지 완료)

- src/main/java/com/sw/cmc/adapter/in/battle/web/BattleControllerImpl.java
- src/main/java/com/sw/cmc/adapter/in/review/ReviewControllerImpl.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/domain/battle/BattleDomain.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/java/com/sw/cmc/entity/Battle.java
- src/main/java/com/sw/cmc/entity/Review.java
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> 🚑️: db 변경으로 인한 배틀, 리뷰 서비스 로직 수정

- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepository.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepositoryImpl.java
- src/main/java/com/sw/cmc/application/port/in/lcd/DeleteLcdCase.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveCodingUseCase.java
- src/main/java/com/sw/cmc/application/port/in/redis/RedisUseCase.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/application/service/redis/RedisService.java
- src/main/resources/openapi_cmc/dto/lcd/LiveCodingDTO.yaml
라이브코딩 삭제 api 개발 
related to #39
> ✨: 라이브코딩 삭제 api 개발

- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepository.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepositoryImpl.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveCodingUseCase.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingDomain.java
- src/main/resources/openapi_cmc/dto/lcd/LiveCodingDTO.yaml
- src/main/resources/openapi_cmc/livecoding.yaml
라이브코딩 방 조회 api 개발
related to #34
> ✨: 라이브코딩 방 조회 api 개발

- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/lcd/LiveCodingUseCase.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingDomain.java
- src/main/resources/openapi_cmc/dto/lcd/LiveCodingDTO.yaml
라이브코딩 방 업데이트 api 개발 (참가/나가기)
related to #43
> ✨: 라이브코딩 방 업데이트 

- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
> ✨리뷰 상세 조회 API 개발중 | 불 필요한Validation method 통합

- src/main/java/com/sw/cmc/adapter/in/lcd/web/LiveCodingControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/lcd/persistence/LiveCodingRepositoryImpl.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingDomain.java
- src/main/resources/openapi_cmc/dto/lcd/LiveCodingDTO.yaml
링크필드,  소스코드 필드 추가 
related to #197
> ✅ : 라이브코딩 링크, 소스코드 필드 추가

- src/main/java/com/sw/cmc/adapter/in/review/web/ReviewControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/review/persistence/ReviewRepository.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/domain/review/ReviewDetailVo.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> 🔨: 리뷰 상세 api 수정

- src/main/java/com/sw/cmc/adapter/in/user/web/LoginControllerImpl.java
> ✨: HTTP ONLY 쿠키 적용

- src/main/java/com/sw/cmc/adapter/in/user/web/LoginControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/user/LoginUseCase.java
- src/main/java/com/sw/cmc/application/service/user/LoginService.java
- src/main/resources/application.yaml
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
- src/main/resources/openapi_cmc/dto/user/LoginDTO.yaml
- src/main/resources/openapi_cmc/user.yaml
> ✨: 배틀 투표 수정

- src/main/java/com/sw/cmc/adapter/out/battle/persistence/BattleRepository.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
> ✨: 배틀 리스트 api 수정

- src/main/java/com/sw/cmc/adapter/in/battle/web/BattleControllerImpl.java
- src/main/java/com/sw/cmc/application/port/in/battle/BattleUseCase.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/resources/openapi_cmc/battle.yaml
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
> ✨: 배틀 투표 상태 api 및 배틀 단건 조회 수정

- src/main/java/com/sw/cmc/CmcApplication.java
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ⚡️ 댓글 리스트 api output 개선

- src/main/java/com/sw/cmc/adapter/in/battle/web/BattleControllerImpl.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/java/com/sw/cmc/domain/battle/BattleDomain.java
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
> ✨: 배틀 수정 api

- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
단 건 조회 시 required 조건 파라미터 추가
#212
> ✨리뷰 조회 yaml파일 CamelCase로 수정함.

- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ✅: 댓글 생성 api in/out 스펙 수정

- src/main/java/com/sw/cmc/application/service/like/LikeService.java
- src/main/java/com/sw/cmc/domain/like/LikeDomain.java
- src/main/resources/application.yaml
- src/main/resources/openapi_cmc/dto/like/LikeDTO.yaml
> ✨: 좋아요 api 스펙 변경, 상태 조회 api 기능 추가

- src/main/java/com/sw/cmc/adapter/out/review/persistence/ReviewRepository.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/domain/review/ReviewDetailVo.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> ✨리뷰 상세 조회 API 수정 | userNum Response 값으로 받아오도록 수정

- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> ✨리뷰 API 컬럼 변경 | UserNum

- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
> ✨리뷰 삭제 API 변경 | service단 reviewDomain -> found 로 변경 적용(테스트 완료)

- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketControllerImpl.java
> 🔨: 라이브코딩 세션 새로고침시에도 연결유지 - 지연 현상 수정

- src/main/java/com/sw/cmc/adapter/in/user/web/UserControllerImpl.java
- src/main/resources/openapi_cmc/dto/user/UserDTO.yaml
> ✨: 회원 정보 변경 api input 변경

- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketControllerImpl.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingAction.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingChatDomain.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingChatType.java
> 호스트 퇴장 시 세션삭제 

- src/main/java/com/sw/cmc/adapter/in/user/web/UserControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/battle/persistence/BattleRepository.java
- src/main/java/com/sw/cmc/application/service/battle/BattleService.java
- src/main/java/com/sw/cmc/application/service/group/GroupService.java
- src/main/java/com/sw/cmc/common/config/SecurityConfig.java
- src/main/java/com/sw/cmc/common/filter/JwtAuthenticationFilter.java
- src/main/java/com/sw/cmc/common/util/SmtpUtil.java
- src/main/java/com/sw/cmc/domain/battle/BattleDetailVo.java
- src/main/java/com/sw/cmc/domain/battle/BattleDomain.java
- src/main/java/com/sw/cmc/domain/user/UserDomain.java
- src/main/resources/openapi_cmc/dto/battle/BattleDTO.yaml
> ⚡️: 배틀 이미지 output 추가

- src/main/java/com/sw/cmc/adapter/out/review/persistence/ReviewRepository.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/common/config/SecurityConfig.java
- src/main/java/com/sw/cmc/domain/review/ReviewDetailVo.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/java/com/sw/cmc/domain/review/ReviewListVo.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> ⚡️: 리뷰 > 유저 이미지

- src/main/java/com/sw/cmc/adapter/in/notice/event/NoticeEventListener.java
- src/main/java/com/sw/cmc/adapter/in/review/web/ReviewControllerImpl.java
- src/main/java/com/sw/cmc/adapter/out/group/persistence/GroupMemberRepository.java
- src/main/java/com/sw/cmc/application/port/in/notice/NoticeUseCase.java
- src/main/java/com/sw/cmc/application/service/notice/NoticeService.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/common/util/NotiUtil.java
- src/main/java/com/sw/cmc/common/util/UserUtil.java
- src/main/java/com/sw/cmc/domain/notice/NoticeDomain.java
- src/main/java/com/sw/cmc/domain/review/ReviewDomain.java
- src/main/java/com/sw/cmc/event/notice/SendNotiInAppEventList.java
- src/main/resources/openapi_cmc/dto/review/ReviewDTO.yaml
> ✨ : 리뷰 대상 이벤트 관련 작업

- src/main/java/com/sw/cmc/adapter/out/comment/persistence/CommentRepository.java
- src/main/java/com/sw/cmc/application/service/comment/CommentService.java
- src/main/java/com/sw/cmc/domain/comment/CommentDomain.java
- src/main/java/com/sw/cmc/domain/comment/CommentVo.java
- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ✨: 댓글 > 유저 이미지 관련 작업

- src/main/resources/openapi_cmc/dto/comment/CommentDTO.yaml
> ✨: 댓글 api 수정

- README.md
> 📝: Readme 작성

- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
> ♻️: 실시간 공유 리팩토링

- src/main/java/com/sw/cmc/domain/battle/BattleDomain.java
> 🔨: 배틀 생성 validation 수정

- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
> 🔨: 실시간 공유 api 수정

- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketControllerImpl.java
> ✅ : 라이브코딩 새로고침 delay 변경

- src/main/resources/init_data/init_data.sql
> ✨: 알림 템플릿 추가

- src/main/java/com/sw/cmc/adapter/in/ai/event/AIEventListener.java
- src/main/java/com/sw/cmc/adapter/in/notice/event/NoticeEventListener.java
- src/main/java/com/sw/cmc/adapter/out/ai/persistence/AIRepository.java
- src/main/java/com/sw/cmc/application/port/in/ai/AIUseCase.java
- src/main/java/com/sw/cmc/application/service/ai/AIService.java
- src/main/java/com/sw/cmc/application/service/review/ReviewService.java
- src/main/java/com/sw/cmc/common/util/AIUtil.java
- src/main/java/com/sw/cmc/common/util/GzipUtil.java
- src/main/java/com/sw/cmc/domain/ai/AIDomain.java
- src/main/java/com/sw/cmc/entity/AIComment.java
- src/main/java/com/sw/cmc/event/ai/CreateCommentEvent.java
- src/main/resources/schema.sql
> ✨ : [AI] API_USER_0100 - AI 답변 등록 개발

- src/main/java/com/sw/cmc/common/config/SecurityConfig.java
> ✨ : 인증 오류 에러메세지 분기

- src/main/java/com/sw/cmc/adapter/in/lcd/web/WebSocketBroadcaster.java
- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
- src/main/java/com/sw/cmc/domain/lcd/LiveCodingChatDomain.java
- src/main/resources/application-prod.yaml
updateLiveCodingSnippet  수정
초대링크 도메인 변경
#355
> [라이브코딩] 상용 수정사항

- src/main/java/com/sw/cmc/application/service/ai/AIService.java
- src/main/java/com/sw/cmc/domain/ai/AIDomain.java
> ✨: ai 댓글 적용

- src/main/resources/application-prod.yaml
> 🔨 : 초대링크 수정

- src/main/java/com/sw/cmc/application/service/lcd/LiveCodingService.java
> ➕: 라이브 코딩 로그 추가
